package com.travelplaner.nativepreview.domain

import kotlinx.serialization.json.*

/** Snapshot of the existing web defaults in src/App.jsx and src/travelMemory.js. */
internal object WebDefaults {
    val currencies = mapOf(
        "가나" to "GHS",
        "가봉" to "XAF",
        "가이아나" to "GYD",
        "감비아" to "GMD",
        "과테말라" to "GTQ",
        "그레나다" to "XCD",
        "그리스" to "EUR",
        "기니" to "GNF",
        "기니비사우" to "XOF",
        "나미비아" to "NAD",
        "나우루" to "AUD",
        "나이지리아" to "NGN",
        "남아프리카공화국" to "ZAR",
        "남수단" to "SSP",
        "네덜란드" to "EUR",
        "네팔" to "NPR",
        "노르웨이" to "NOK",
        "뉴질랜드" to "NZD",
        "니제르" to "XOF",
        "니카라과" to "NIO",
        "대한민국" to "KRW",
        "덴마크" to "DKK",
        "도미니카" to "XCD",
        "도미니카공화국" to "DOP",
        "독일" to "EUR",
        "동티모르" to "USD",
        "라오스" to "LAK",
        "라트비아" to "EUR",
        "러시아" to "RUB",
        "레바논" to "LBP",
        "레소토" to "LSL",
        "루마니아" to "RON",
        "룩셈부르크" to "EUR",
        "르완다" to "RWF",
        "리비아" to "LYD",
        "라이베리아" to "LRD",
        "리투아니아" to "EUR",
        "리히텐슈타인" to "CHF",
        "마다가스카르" to "MGA",
        "마셜 제도" to "USD",
        "마카오" to "MOP",
        "말라위" to "MWK",
        "말레이시아" to "MYR",
        "말리" to "XOF",
        "멕시코" to "MXN",
        "모나코" to "EUR",
        "모로코" to "MAD",
        "모리셔스" to "MUR",
        "모리타니" to "MRU",
        "모잠비크" to "MZN",
        "몬테네그로" to "EUR",
        "몰도바" to "MDL",
        "몰디브" to "MVR",
        "몰타" to "EUR",
        "몽골" to "MNT",
        "미국" to "USD",
        "미얀마" to "MMK",
        "미크로네시아" to "USD",
        "바누아투" to "VUV",
        "바레인" to "BHD",
        "바베이도스" to "BBD",
        "바티칸 시국" to "EUR",
        "바하마" to "BSD",
        "방글라데시" to "BDT",
        "베냉" to "XOF",
        "베네수엘라" to "VES",
        "베트남" to "VND",
        "벨기에" to "EUR",
        "벨라루스" to "BYN",
        "벨리즈" to "BZD",
        "보스니아 헤르체고비나" to "BAM",
        "보츠와나" to "BWP",
        "볼리비아" to "BOB",
        "부룬디" to "BIF",
        "부르키나파소" to "XOF",
        "부탄" to "BTN",
        "북마케도니아" to "MKD",
        "북한" to "KPW",
        "불가리아" to "BGN",
        "브라질" to "BRL",
        "브루나이" to "BND",
        "사모아" to "WST",
        "산마리노" to "EUR",
        "사우디아라비아" to "SAR",
        "상투메 프린시페" to "STN",
        "세네갈" to "XOF",
        "세르비아" to "RSD",
        "세이셸" to "SCR",
        "세인트루시아" to "XCD",
        "세인트빈센트 그레나딘" to "XCD",
        "세인트키츠 네비스" to "XCD",
        "소말리아" to "SOS",
        "솔로몬 제도" to "SBD",
        "수단" to "SDG",
        "수리남" to "SRD",
        "스리랑카" to "LKR",
        "스웨덴" to "SEK",
        "스위스" to "CHF",
        "스페인" to "EUR",
        "슬로바키아" to "EUR",
        "슬로베니아" to "EUR",
        "시리아" to "SYP",
        "시에라리온" to "SLE",
        "싱가포르" to "SGD",
        "아랍에미리트" to "AED",
        "아르메니아" to "AMD",
        "아르헨티나" to "ARS",
        "아이슬란드" to "ISK",
        "아이티" to "HTG",
        "아일랜드" to "EUR",
        "아제르바이잔" to "AZN",
        "아프가니스탄" to "AFN",
        "안도라" to "EUR",
        "앤티가 바부다" to "XCD",
        "알바니아" to "ALL",
        "알제리" to "DZD",
        "앙골라" to "AOA",
        "에콰도르" to "USD",
        "에리트레아" to "ERN",
        "에스토니아" to "EUR",
        "에스와티니" to "SZL",
        "에티오피아" to "ETB",
        "엘살바도르" to "USD",
        "영국" to "GBP",
        "예멘" to "YER",
        "오만" to "OMR",
        "오스트리아" to "EUR",
        "온두라스" to "HNL",
        "요르단" to "JOD",
        "우간다" to "UGX",
        "우루과이" to "UYU",
        "우즈베키스탄" to "UZS",
        "우크라이나" to "UAH",
        "이라크" to "IQD",
        "이란" to "IRR",
        "이스라엘" to "ILS",
        "이집트" to "EGP",
        "이탈리아" to "EUR",
        "인도" to "INR",
        "인도네시아" to "IDR",
        "일본" to "JPY",
        "자메이카" to "JMD",
        "잠비아" to "ZMW",
        "적도 기니" to "XAF",
        "조지아" to "GEL",
        "중국" to "CNY",
        "중앙아프리카공화국" to "XAF",
        "지부티" to "DJF",
        "짐바브웨" to "ZWG",
        "차드" to "XAF",
        "칠레" to "CLP",
        "카메룬" to "XAF",
        "카보베르데" to "CVE",
        "카자흐스탄" to "KZT",
        "카타르" to "QAR",
        "캄보디아" to "KHR",
        "캐나다" to "CAD",
        "케냐" to "KES",
        "코모로" to "KMF",
        "코트디부아르" to "XOF",
        "코스타리카" to "CRC",
        "코소보" to "EUR",
        "콜롬비아" to "COP",
        "콩고 공화국" to "XAF",
        "콩고 민주공화국" to "CDF",
        "쿠바" to "CUP",
        "쿠웨이트" to "KWD",
        "크로아티아" to "EUR",
        "키르기스스탄" to "KGS",
        "키리바시" to "AUD",
        "키프로스" to "EUR",
        "타지키스탄" to "TJS",
        "탄자니아" to "TZS",
        "태국" to "THB",
        "터키" to "TRY",
        "토고" to "XOF",
        "통가" to "TOP",
        "투르크메니스탄" to "TMT",
        "투발루" to "AUD",
        "튀니지" to "TND",
        "트리니다드 토바고" to "TTD",
        "파나마" to "PAB",
        "파라과이" to "PYG",
        "파키스탄" to "PKR",
        "파푸아뉴기니" to "PGK",
        "팔라우" to "USD",
        "팔레스타인" to "ILS",
        "페루" to "PEN",
        "포르투갈" to "EUR",
        "폴란드" to "PLN",
        "프랑스" to "EUR",
        "피지" to "FJD",
        "핀란드" to "EUR",
        "필리핀" to "PHP",
        "헝가리" to "HUF",
        "호주" to "AUD",
        "홍콩" to "HKD",
        "괌/사이판" to "USD",
        "대만" to "TWD"
    )
    fun fields(country: String) = buildJsonObject {
        put("reserveItems", JsonArray(emptyList()))
        put("budgetSettings", buildJsonObject {
            put("limitKRW", 1000000)
            put("travelCurrency", currencies[country] ?: "USD")
        })
        put("expenses", JsonArray(emptyList()))
        put("settlementParticipants", buildJsonArray {
            add(buildJsonObject { put("id", "self"); put("name", "나") })
        })
        put("checklist", buildJsonArray {
            listOf(
                "passport" to "여권 및 신분증",
                "insurance" to "여행자 보험",
                "charger" to "충전기·보조배터리",
                "cash" to "환전·현금 준비",
                "reservation" to "예약·티켓 확인",
            ).forEach { (id, label) ->
                add(buildJsonObject { put("id", id); put("label", label); put("checked", false) })
            }
        })
        put("travelDetails", buildJsonObject {
            listOf("departure", "arrival", "flightNumber", "stayName", "stayAddress").forEach { put(it, "") }
        })
        put("journalEntries", JsonArray(emptyList()))
        put("reminders", buildJsonObject { put("enabled", false); put("minutesBefore", 30) })
    }
}
